### ISSUE TITLE
Makefile syntax highlighting partially breaks when a # is in a string

### ISSUE THREAD

**Issue by alexr00** [fadeevab/make.tmbundle#9] opened 2020-10-21 12:49 UTC
Originally from @tristan957 in https://github.com/microsoft/vscode/issues/108749

Steps to Reproduce:

1. Open a Makefile
2. Type in the following
```make
define config-gen =
	( echo '# Note: When a variable is set multiple times in this file' ;\
	  echo '#       it is the *first* setting that sticks!' ;\
  )
endef
```

Does this issue occur when all extensions are disabled?: Yes

The second echo statement is colored to look like a comment. You can see it is even broken in the GitHub syntax. I am no expert at textmake language files, but https://github.com/microsoft/vscode/blob/master/extensions/make/syntaxes/make.tmLanguage.json#L41 seems to tell me that a comment beginning with a # doesn't look behind itself to see if it is in a string.

**Comment by fadeevab** [comment] 2020-11-02 07:33
@tristan957 Hi! The only way to fix it is disabling comments highlighting inside of `define` block. Because `define` block allows to put there any semantics in any language, so it's extremely hard to analyze the syntax there. And it would be correct I think

**Comment by tristan957** [comment] 2020-11-03 05:25
@fadeevab well this is unfortunate. Textmate grammars continue to disappoint. Thanks for looking into this. Even more reason for my projects at work to move to Meson :). @alexr00 thanks for moving issue to the right place.

**Comment by fadeevab** [comment] 2020-11-04 16:42
@tristan957 Don't blame Textmate :), the issue is really in the nature of Makefile: it is kind of a context-dependent formal grammar which can barely be described with regular expressions. Like, you look at the string, and you realize that it's probably bash syntax, but how can it be identified from inside of Textmate grammar for Makefile? So we just try to highlight at least `$(variables)` inside of `define`-`endef` block, and as you can see there are edge cases about all other tokens.

So I can just disable comments highlighting inside of `define` block. What do you think? Would it be okay for you, or maybe no need to touch it?

**Comment by tristan957** [comment] 2020-11-04 16:52
Admittedly I am not super familiar with make syntax, but could you not just have the `#` comment out the rest of the line? In the picture of the original issue, the first `#` comments out all subsequent lines until the endef?

I am also fine with doing nothing, but damn :(.

**Comment by fadeevab** [comment] 2020-11-10 14:25
@tristan957 That's the thing that it's almost impossible unless I implement the bash syntax analyzer into the Makefile syntax. This is because in the Makefile syntax any comment starts from `#` regardless where is the `#` inserted. Just check it out:

```
a:=out"#put"

$(info $(a))
```

Output is:
```
out"
```
Makefile doesn't care about `"` - it's just a symbol.

The only way out I see: disable comments in the `ifdef` section highlighting.

**Comment by tristan957** [comment] 2020-11-10 15:55
A "Won't fix" is just fine. Make syntax is truly unbelievably horrid

**Comment by fadeevab** [comment] 2021-02-06 13:50
Fixed! Thank you all.

**Closed as completed by fadeevab** 2021-02-06 13:50 UTC
